### ISSUE TITLE
New reviews from editorial communities are not present

### ISSUE THREAD

**Issue by giorgiosironi** [hivereview/thehive#192]
Our hardcoded data slowly becomes out of date until a human corrects it e.g. by looking at https://hypothes.is/groups/q5X6RWJ6/elife and there is no way for that human to know if it is out date.

**Comment by thewilkybarkid** [comment]
Reviews stored in 3 places:

- Crossref (eg PeerJ)
- DataCite (eg Zenodo)
- Hypothes.is (eg eLife)

We need to be able to find these, _and_ what bioRxiv article they refer to. PeerJ reviews probably link to the PeerJ article rather than the preprint, if anything.

There is a difference between finding out about historical reviews and future ones (the former will require scraping, the latter could be through notifications).

**Comment by thewilkybarkid** [comment]
For notifications, Crossref event data (https://www.crossref.org/services/event-data/) might be a possibility.

**Comment by thewilkybarkid** [comment]
eLife reviews on Hypothes.is: https://hypothes.is/groups/q5X6RWJ6/elife
PREreview: seemingly no way to list most recent reviews, have to keep an eye on https://www.prereview.org/
PeerJ: can't see any search options on their site
Review Commons reviews on Hypothes.is: https://hypothes.is/groups/NEGQVabn/review-commons

**Comment by thewilkybarkid** [comment]
EuropePMC allows listing of Peer Community In recommended articles (https://europepmc.org/search?query=%28LABS_PUBS%3A%221826%22%29&page=1&sortBy=FIRST_PDATE_D%2Bdesc), though seems to stop in Dec 2019.

**Comment by thewilkybarkid** [comment]
So, probably a _lot_ of work to automate. Given the low volume of content, better as a manual task.

**Comment by giorgiosironi** [comment]
Removing from Todo, to reprioritize according to the opportunities tree.
