### ISSUE TITLE
Display summary of reviews by eLife

### ISSUE THREAD

**Issue by thewilkybarkid** [hivereview/thehive#243]
Show a hard-coded 'Summary of reviews by eLife' on http://staging.hive.review/articles/10.1101/2020.06.19.160770 containing the summary text of https://hypothes.is/a/CZT9jPdTEequMgu20M5Zmg

- [x] Hardcoded
- [ ] Apply correct semantics to HTML
- [ ] Use CSS rather than empty HTML elements to introduce whitespace
- [ ] Detect when a "review" is actually a summary

**Comment by BlueReZZ** [comment]
Manually removed the review summary from the eLife review CSV file since we hardcoded it into the renderer. This is just temporary until we either a) fix that situation by detecting the difference between a summary and a review or b) don't care about the duplication. There's a demo tomorrow (18/09/2020) that would benefit from the removal so we did that today.

**Comment by davidcmoulton** [comment]
> Manually removed the review summary from the eLife review CSV file since we hardcoded it into the renderer. This is just temporary until we either a) fix that situation by detecting the difference between a summary and a review or b) don't care about the duplication. There's a demo tomorrow (18/09/2020) that would benefit from the removal so we did that today.

The commit in question is https://github.com/hivereview/thehive/commit/80815cede451594fada784bf053a629da4bb11cd.
